# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-09 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20190909_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='rpi_type',
            field=models.CharField(choices=[(b'analog', b'Analog'), (b'digital', b'Digital')], default=b'analog', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
