# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-09 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20190909_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='plot_y_axis_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
