# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-29 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_sensor_plot_y_axis_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rpi_port', models.IntegerField()),
                ('rpi_type', models.CharField(choices=[(b'analog', b'Analog'), (b'digital', b'Digital')], default=b'digital', max_length=100)),
                ('state', models.CharField(choices=[(b'on', b'On'), (b'off', b'Off')], default=b'off', max_length=4)),
            ],
        ),
    ]
