# Generated by Django 3.0.7 on 2020-06-14 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_auto_20200613_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='plots')),
                ('measurements', models.ManyToManyField(blank=True, to='collect.Measurement')),
            ],
        ),
    ]
