# Generated by Django 3.0.7 on 2020-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0009_plotfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotfile',
            name='measurements',
            field=models.ManyToManyField(blank=True, related_name='plots', to='collect.Measurement'),
        ),
    ]
